spin_manifest_version = 2

[application]
name = "cron"
version = "0.1.0"
authors = ["Thorsten Hans <thorsten.hans@fermyon.com>"]
description = ""

[[trigger.command]]
component = "job"

[component.job]
source = "target/wasm32-wasi/release/job.wasm"
allowed_outbound_hosts = ["https://myip.fermyon.app/"]
build = ["cargo component build --target wasm32-wasi --release"]
